"""
Django settings for charity_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-lbi6l(9=m3&))vqn9a7s+1p786f8-e)%j9y%kgjgshi@eekb2l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # NOTE: 'django.contrib.admin' is intentionally NOT included here.
    # This project uses its own custom-built admin panel (see charity_app/urls.py -> /myadmin/)
    # instead of Django's default admin site.
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'charity_app',  # our custom charity donation app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # We replace Django's default SessionMiddleware with our own DualSessionMiddleware.
    # This lets a DONOR and a STAFF member stay logged in AT THE SAME TIME in the
    # same browser, by giving the admin panel ("/myadmin/...") its own separate
    # session cookie instead of sharing the donor site's cookie.
    # See charity_app/middleware.py for the full explanation.
    'charity_app.middleware.DualSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'charity_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'charity_app.context_processors.site_settings',
                'charity_app.context_processors.user_profile',
            ],
        },
    },
]

WSGI_APPLICATION = 'charity_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'b8itubcnzjvycuga2yon',
        'USER': 'urjrohesshkd6enc',
        'PASSWORD': 'btzGHAhO0GkQLo3fY3wo',
        'HOST': 'b8itubcnzjvycuga2yon-mysql.services.clever-cloud.com',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Extra folders where Django will look for static files (besides each app's static/ folder)
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (user-uploaded campaign images)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default field type for auto-created primary keys
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ---- Authentication redirects ----
LOGIN_URL = 'login'                # where @login_required sends non-logged-in users
LOGIN_REDIRECT_URL = 'dashboard'   # where users go after logging in
LOGOUT_REDIRECT_URL = 'home'       # where users go after logging out

# ---- Email Configuration (Console backend for development) ----
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "rohanberad5@gmail.com"
EMAIL_HOST_PASSWORD = "zxobewrrqrlymfmq"

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# pyment integration 
RAZORPAY_KEY_ID = "rzp_test_TLhS4kqWUsTnMT"
RAZORPAY_KEY_SECRET = "aDbAycta4AeH5WB3f8NtVY0I"
