# Generated by Django 6.0.7 on 2026-07-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_line1', models.CharField(default='Together We Can', max_length=100)),
                ('hero_title_highlight', models.CharField(default='Create a Better World', max_length=100)),
                ('hero_subtitle', models.TextField(default="Your small contribution can make a big difference in someone's life. Join us in our mission to help the needy.")),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('stat_campaigns', models.CharField(default='500+', help_text='e.g. 500+', max_length=20)),
                ('stat_lives_impacted', models.CharField(default='50,000+', max_length=20)),
                ('stat_funds_raised', models.CharField(default='Rs. 2.5 Cr+', max_length=20)),
                ('stat_donors', models.CharField(default='10,000+', max_length=20)),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField(default='We are committed to building a better tomorrow by supporting education, healthcare, animal welfare, and disaster relief initiatives. Together, we can bring hope and create lasting change.')),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('ngo_name', models.CharField(default='Helping Hands', max_length=100)),
                ('footer_about_text', models.TextField(default='Together we can create a better world for everyone.')),
                ('contact_address', models.CharField(default='123 Hope Street, Mumbai, India', max_length=200)),
                ('contact_email', models.EmailField(default='contact@helpinghands.org', max_length=254)),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_role', models.CharField(default='Regular Donor', max_length=100)),
                ('message', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='A number from 1 to 5')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True, help_text='Only active testimonials are shown on the home page')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
