# Generated by Django 6.0.7 on 2026-08-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0005_donation_razorpay_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_date',
        ),
    ]
