# Generated by Django 6.0.7 on 2026-08-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0006_remove_donation_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_date',
            field=models.DateTimeField(auto_now_add=True, default=12),
            preserve_default=False,
        ),
    ]
