# Generated by Django 6.0.7 on 2026-08-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0007_donation_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading',
            field=models.CharField(default='About Us', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(
                default=(
                    "Founded with a simple belief -- that everyone deserves a fair chance at "
                    "a better life -- we have spent years working directly with communities on "
                    "education, healthcare, animal welfare, and disaster relief. Every rupee "
                    "donated here is tracked, and every campaign is reviewed by our team before "
                    "it goes live."
                )
            ),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='registration_number',
            field=models.CharField(
                blank=True, default='',
                help_text='e.g. NGO Registration / 80G Number, shown on the About page',
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_active', models.BooleanField(default=True, help_text='Only active FAQs are shown on the FAQ page')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
