# Generated by Django 6.0.8 on 2026-08-06 06:52

import charity_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0008_faq_contactmessage_sitesettings_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('diagnosis_condition', models.CharField(help_text="Typed in freely by the requester, e.g. 'Kidney Cancer'", max_length=200)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('treatment_stage', models.CharField(choices=[('pre_op', 'Pre-op'), ('active', 'Active'), ('recovery', 'Recovery')], default='active', max_length=10)),
                ('document', models.FileField(blank=True, help_text='Supporting document -- medical report, bill, prescription, etc.', null=True, upload_to=charity_app.models.help_request_document_path)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes, not shown to the requester')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
