# Generated by Django 6.0.7 on 2026-08-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0009_helprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_1_name',
            field=models.CharField(default='Founder', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_1_photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_1_role',
            field=models.CharField(default='Vision & Strategy', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_2_name',
            field=models.CharField(default='Program Lead', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_2_photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_2_role',
            field=models.CharField(default='Program Design & Impact', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_3_name',
            field=models.CharField(default='Operations', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_3_photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_3_role',
            field=models.CharField(default='Administration & Finance', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_4_name',
            field=models.CharField(default='Volunteers', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_4_photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_member_4_role',
            field=models.CharField(default='Community Champions', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_section_subtitle',
            field=models.TextField(default='A dedicated mix of staff and volunteers driven by compassion and accountability.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='team_section_title',
            field=models.CharField(default='Meet the Team', max_length=100),
        ),
    ]
