# Generated by Django 6.0.7 on 2026-08-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0010_sitesettings_team_member_1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve a public testimonial before it can be published'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only active testimonials are shown on the home page'),
        ),
    ]
