# Generated by Django 6.0.8 on 2026-08-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0011_testimonial_is_approved_testimonial_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('education', 'Education'), ('medical', 'Medical Help'), ('animal', 'Animal Rescue'), ('disaster', 'Disaster Relief'), ('food_shelter', 'Food & Shelter')], default='general', help_text='Controls the colored badge shown on the story card.', max_length=20),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(blank=True, help_text='Not shown publicly -- used by staff to follow up if needed', max_length=254),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='story_title',
            field=models.CharField(blank=True, help_text='Optional headline shown on the story card. Staff can add this while approving a submission.', max_length=150),
        ),
    ]
