# Generated by Django 6.0.8 on 2026-08-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0012_testimonial_category_testimonial_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading_highlight',
            field=models.CharField(default='people in need.', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_story_quote',
            field=models.CharField(default='You Can Be the Reason Someone Smiles Today.', help_text="Short quote shown over the 'Our Story' photo", max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_video_url',
            field=models.URLField(blank=True, default='', help_text="Optional YouTube/Vimeo embed link for the 'Watch Our Story' button"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_vision_text',
            field=models.TextField(default='To create a future where every person has access to basic needs, education, and opportunity -- no matter where they live. We envision a just and compassionate world where communities thrive with dignity.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_partners_volunteers',
            field=models.CharField(default='250+', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_heading',
            field=models.CharField(default='We stand with', max_length=100),
        ),
    ]
