# Generated by Django 6.0.7 on 2026-08-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0013_sitesettings_about_heading_highlight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('contact_message', 'New Contact Message'), ('donation', 'New Donation'), ('help_request', 'New Help Request'), ('story_submission', 'New Story Submission')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=500)),
                ('url', models.CharField(help_text='Admin page to redirect to when clicked', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
