# Generated by Django 6.0.8 on 2026-08-17 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0014_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='updates/')),
                ('publish_date', models.DateField(default=django.utils.timezone.localdate, help_text="Shown on the card, e.g. 'June 12, 2025'")),
                ('link_url', models.CharField(blank=True, help_text="Optional -- where the card links to. Leave blank if it's just a headline.", max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Only active updates are shown on the home page')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-publish_date'],
            },
        ),
    ]
