# Generated by Django 6.0.7 on 2026-08-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0015_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio about the user'),
        ),
    ]
