# Generated by Django 6.0.8 on 2026-08-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0016_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='The full letter to donors. Supports basic formatting (bold, italic, lists, links).')),
                ('image', models.ImageField(blank=True, null=True, upload_to='appeals/')),
                ('is_published', models.BooleanField(default=False, help_text='Only published appeals appear on the website')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(help_text='Donations made from this appeal are recorded against this campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='donation_appeals', to='charity_app.campaign')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppealSupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('ltr', 'Litre'), ('ml', 'ml'), ('pcs', 'Pieces'), ('packet', 'Packet'), ('box', 'Box'), ('unit', 'Unit')], default='kg', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_items', to='charity_app.donationappeal')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
