# Generated by Django 6.0.7 on 2026-08-22 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0017_donationappeal_appealsupplyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='appeal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='charity_app.donationappeal'),
        ),
        migrations.AddField(
            model_name='donationappeal',
            name='raised_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='charity_app.campaign'),
        ),
        migrations.AlterField(
            model_name='donationappeal',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Donations made from this appeal are recorded against this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_appeals', to='charity_app.campaign'),
        ),
    ]
