# Generated by Django 6.0.7 on 2026-08-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0018_donation_appeal_donationappeal_raised_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationappeal',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='appeals/'),
        ),
        migrations.AddField(
            model_name='donationappeal',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='appeals/'),
        ),
        migrations.AddField(
            model_name='donationappeal',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='appeals/'),
        ),
    ]
